title: Francesco Maida
description: >
  Puoi pensarmi come unâ€™estetista per aziende: lavoro con dedizione 
  per rendere bella e desiderabile la tua impresa agli occhi delle 
  persone, cosÃ¬ che tu possa vendere di piÃ¹.
base-url: https://cesco.it

support:
  url: https://assistenza.cesco.it
  phone: +39 352 00 68000
  email: museo05_vasto@icloud.com

# Prezzi all'ora del mio lavoro
fares:
  standard: 75
  discounted: 60

author:
  name: Francesco Maida
  avatar: images/avatar.jpg
  job: >
    Consulente digitale per aziende (siti web, social e comunicazione online)
  description: >
    Mi chiamo Francesco. Puoi pensarmi come unâ€™estetista 
    per aziende: lavoro con cura e dedizione per rendere 
    bella e desiderabile la tua impresa agli occhi delle 
    persone, cosÃ¬ che tu possa vendere di piÃ¹. Non infiocchetto, 
    nÃ© creo illusioni: faccio emergere il meglio della tua azienda, 
    raccontandone con autenticitÃ  e passione la missione.
  cv: downloads/cv.pdf


roles:
  - uno sviluppatore web
  - un designer grafico
  - un creatore di contenuti

social:
  #- icon: fa-instagram
  #  url: #
  - icon: fa-linkedin
    url: https://www.linkedin.com/in/francesco.maida
  - icon: fa-github
    url: https://github.com/fmaida
  - icon: fa-mastodon
    url: "https://livellosegreto.it/@cesco"

skills:
  - title: Sviluppo web (HTML + CSS + Javascript)
    value: 85
  - title: Python
    value: 80
  - title: FileMaker
    value: 70

testimonials:
  - name: John Doe
    role: CEO of Example Inc.
    image: images/icons/account.svg
    comment: >
      I enjoyed working with Francesco Maida 
      and he made my project a success. Good luck Francesco ðŸ‘
  - name: Jane Doe
    role: Product Designer at Google Inc.
    image: images/icons/account.svg
    comment: >
      He's a genious and a wonderful person to work with. 
      Glad you entered my life and my team, Francesco!

brands:
  - name: Google
    image: images/brands/google.svg
  - name: Facebook
    image: images/brands/facebook.svg
  - name: Twitter
    image: images/brands/twitter.svg
  - name: Instagram
    image: images/brands/instagram.svg

contact:
  title: Contattami per un preventivo gratuito
  description: >
    Faremo una breve chiacchierata: 
    alla fine dellâ€™incontro ti presenterÃ² 
    subito alcune prime soluzioni. Se per 
    risponderti in modo accurato dovrÃ² 
    raccogliere ulteriori informazioni 
    (su costi o modalitÃ ), ti invierÃ² la 
    proposta completa nelle ore o nei giorni successivi.<br><br>
    Non vuoi usare il modulo? Inviami una  
    <a href="mailto:{{ params.support.email }}?subject=Ho%20visto%20il%20sito%20web%20e%20ho%20delle%20domande">email</a>. ðŸ‘‹

fiscal:
  locality: Venezia
  region: VE
  postal-code: 30132
  country: IT
  partita-iva: 04908370275

settings:
  space: 30 # Spazio fra titolo e descrizione delle sezioni